# Generated by Django 3.2.15 on 2022-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='img',
            field=models.ImageField(default='ghgd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
